<?php
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
	'default_font_size' => 13,
	'default_font' => 'domine'
]);

$nokhtml = '
<style>
body {
	font-family: domine;
	font-size: 13px;
	padding :0; margin: 0;
}

.col1, .col2, .col3, .col4, .col5, .col6{
	float:left;
	width:40%
}
h1, h2, h3, h4, h5, h6 {
padding-left: 20px;
margin : 0;
}

.floatleft{
	float:left;
}

.floatright{
	float:right;
}
table {
	font-family: domine;
	border-collapse: collapse;
	width: 100%;
    
  }
  
  
th ,td{
    border-top: 1px solid #d1eaf5;
   
    text-align: center;
	padding: 8px;
  }
  img {
    padding: right 10px;
  }

  </style>

  <body>

  <htmlpagefooter name="myfooter">
  <div style="border-top: 1px solid #333333; font-size: 9pt; text-align: center; padding-top: 1mm; ">
  Page {PAGENO} of {nb}
  </div>
  </htmlpagefooter>
  
  <sethtmlpageheader name="myheader" value="on" show-this-page="1" />
  <sethtmlpagefooter name="myfooter" value="on" />
  
<div class="row">
<div class="col1">
<img src="iv6.png" width="200" />
<br />
<br />
<div class="date"><h2>DATE : 04/11/2021</h2></div>
<div class="due date"><h2>DUE DATE : 18/11/2021</h2></div>
<hr style="color:#00a9d3;">


<div class="invoice to"><b>INVOICE TO :</b>name customer</div>
<div class="address"><b>ADDRESS :</b> ........</div>
<div class="tel"><b>TEL :</b>  000 000 0000</div>
<div class="email"><b>EMAIL :</b> customer@gmail.com</div>

</div>

<div class="col2 floatright">

<img src="tenth.png" width="240" />
<p>Tenthmatrix Ltd. ,The Coach House, 77A Marlowes <br />Hemel Hempstead Herts, HP1 1LF<br />Email: billing@tenthmatrix.co.uk<br />Tel: 44 1442 384 149</p>

<div class="invoice no"><h3>INVOICE NO : 12345</h3></div>
<div class="project"><h3>PROJECT: New website </h3></div>

</div> 
</div>

<hr style="color:#999999;">

<br />


<!-- INVOICE ITEMS HERE -->

<table class="items" >
<tr>
<td width="10%"><b>PERIOD</b></td>
<td width="50%"><b>DESCRIPTION</b></td>
<td width="10%"><b>UNITS</b></td>
<td width="15%"><b>UNIT PRICE</b></td>
<td width="15%" style="background-color: #d1eaf5;"><b>Amount</b></td>
</tr>

<tr>
  <td>1</td>
  <td>New Website</td>
  <td>1</td>
  <td>&#163;500</td>
  <td style="background-color: #d1eaf5;">&#163;500</td>
</tr>
<tr>
  <td>2</td>
  <td>Domanname</td>
  <td>1</td>
  <td>&#163;50</td>
  <td style="background-color: #d1eaf5;">&#163;50</td>
</tr>
<tr>
<td class="blanktotal" colspan="3" rowspan="6">

</td>
</tr>
<td class="totals">SUBTOTAL (excl. VAT):</td>
<td class="totals" style="background-color: #d1eaf5;">&#163;550</td>
</tr>
<tr>
<td class="totals">VAT 21,00%:</td>
<td class="totals" style="background-color: #d1eaf5;">&#163; 115.5</td>
</tr>

<tr>
<td class="totals"><b>TOTAL:</b></td>
<td class="totals" style="background-color: #d1eaf5;"><b> &#163;665.5</b></td>
</tr>

</table>


<!-- END ITEMS HERE -->

<div class="row" style="background-color: #73c2fb; ">
<div class="col1">
<h2>Thank you for your business.</h2>
</div>

<div class="col2 floatright">
<h2>GRAND TOTAL : &#163;665.5</h2>
</div>
</div>
<hr style="color:#999999;">

<div class="row">
<div class="col1">
<p>Thank you for your business!<br />VAT No.972 9855 56. Bank: HSBC,Sort Code: 40-24-07<br />Account No.91565850</p>
</div>
<div class="col2 floatright">
<p><b>Terms :</b> Please note that our payment terms for this Invoice are NET 15. Interest will be charged on all Invoice that are not paid on time.</p>
</div>
</div>

<h3>Please make payment by electronic transfer to:</h3>

<div class="row">
<div class="col1">

<table class="detail" style="background-color: #d1eaf5;">
<tr>
<td >Bank name :</td>
<td >Tide</td>
</tr>

<tr>
<td >Account name :</td>
<td >Tenmatrix Ltd</td>
</tr>

<tr>
<td>Sort code :</td>
<td>23-69-72</td>
</tr>

<tr>
<td>Account number :</td>
<td>16279782</td>
</tr>

<tr>
<td>Please use reference :</td>
<td>IT CONSUTING-1415</td>
</tr>

</table>
</div>
</div>


<p>Tenmatrix Ltd UK.also trading as Tenmatrix,is a registered company number:11641870. VAT number: GB 361 746 193. Registered in England and Wales. Registered office address: The Coach House,77A Marlowes, Hemel Hempstead, Herts, United Kingdom,HP1 1LF.</p>

<p><b>Note:</b>This Invoice was generated by  Workstation CRM and Invoicing system automatically.</p>
<div class="date">Date: 18/11/2021</div>
<div class="time"> Time: 22:30:05</div>
  </body>

';
//

$mpdf->WriteHTML($nokhtml . $termsHTML);


//

$mpdf->Output();


?>