<?php
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
	'default_font_size' => 16,
	'default_font' => 'inter'
]);


$nokhtml = '
<style>
body {
	font-family: inter;
	font-size: 16px;
	padding :0; margin: 0;
}
.row{
	clear:both;
	overflow:hidden;
}

.col1, .col2, .col3, .col4, .col5, .col6{
	float:left;
	width:40%
}
h1, h2, h3, h4, h5, h6 {
padding: 0;
margin : 0;
}

.floatleft{
	float:left;
}

.floatright{
	float:right;
}
table {
	font-family: inter;
	border-collapse: collapse;
	width: 100%;
  }
  
  td, th {
	border-bottom: 1px solid #c4e4f4;
	text-align: center;
	padding: 8px;
  }
 
  .items td.blanktotal {
    background-color: #FFFFFF;
    border: 0mm none #FFFFFF;
    border-top: 0.1mm solid #FFFFFF;
    border-right: 0.1mm solid #FFFFFF;
	text-align: left;
}
.items td.totals {
    text-align: right;
}
  </style>



<body>

<div class="row">
<div class="col1">
<img src="tenth.png" width="240"  />

<p>Tenthmatrix Ltd. ,The Coach House, 77A Marlowes <br />Hemel Hempstead Herts, HP1 1LF<br />Email: billing@tenthmatrix.co.uk<br />Tel: 44 1442 384 149</p>

</div>

<div class="col2 floatright">
<img src="iv6.png" width="200" />
<hr style="color:#00a9d3;">
<div class="invoice no"><h3>INVOICE NO: ws-0001</h3> 
<div class="date"><h3>DATE : 04/11/2021</h3></div>
<div class="due date"><h3>DUE DATE : 18/11/2021</h3></div> 


</div>
</div>


<htmlpagefooter name="myfooter">
<div style="border-top: 1px solid #333333; font-size: 9pt; text-align: center; padding-top: 1mm; ">
Page {PAGENO} of {nb}
</div>
</htmlpagefooter>

<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter name="myfooter" value="on" />

<div class="row" style="background-color: #c4e4f4; padding: 15px;">

<div class="col1" style="padding: left 20px;">
<div class="invoice to"><b>Invoice To : </b></div>
<div class="address"><b>Address :</b>34160</div>
<div class="tel"><b>Tel: </b>000 000 0000</div>
</div>

<div class="col2 floatright" >
<div class="project"><b>Project :</b> small website design</div>
<div class="vat"><b>VAT number :</b>12345678 </div>
<div class="email"><b>Email: </b>customers@gmail.com</div>
</div>
</div>

<hr style="color:#00a9d3;">






<table class="items">
<tr>
<th width="10%">No</th>
<th width="50%">Description </th>
<th width="10%">Unit</th>
<th width="15%">Unit price</th>
<th width="15%">Total</th>
</tr>

<tr>
<td>1</td>
<td>small website design-one page website (Free hosting and domain name for the first year)</td>
<td>1</td>
<td>&#163;000 </td>
<td>&#163;000 </td>
</tr>

<tr>
<td class="blanktotal" colspan="3" rowspan="6" >
</td>

</tr>

<tr>
<td class="totals">subtotal (excl. VAT):</td>
<td class="totals">&#163;000 </td>
</tr>

<tr>
<td class="totals">VAT 21,00%:</td>
<td class="totals">&#163;</td>
</tr>

<tr>
<td class="totals" style="background-color: #c4e4f4;"><b>Total:</b></td>
<td class="totals" style="background-color: #c4e4f4;"><b>&#163;0000 </b></td>
</tr>

</table>
<hr style="color:#00a9d3;">

<div class="row">
<div class="col1">
<p>Thank you for your business!<br />VAT No.972 9855 56. Bank: HSBC,Sort Code: 40-24-07<br />Account No.91565850</p>

<p><b> terms:</b><br />Please note that our payment terms for this Invoice are NET 15. Interest will be charged on all Invoice that are not paid on time.</p>
</div>

<div class="col2 floatright">
<p><b><i>Please make payment by electronic transfer to :</i></b><br /> 
<table class="detail">
<tr>
<td >Bank name :</td>
<td >Tide</td>
</tr>

<tr>
<td >Account name :</td>
<td >Tenmatrix Ltd</td>
</tr>

<tr>
<td>Sort code :</td>
<td>23-69-72</td>
</tr>

<tr>
<td>Account number :</td>
<td>16279782</td>
</tr>

<tr>
<td>Please use reference :</td>
<td>IT CONSUTING-1415</td>
</tr>

</table>
</div>


</div>
<br />
<p>Tenmatrix Ltd UK.also trading as Tenmatrix,is a registered company number:11641870. VAT number: GB 361 746 193. Registered in England and Wales. Registered office address: The Coach House,77A Marlowes, Hemel Hempstead, Herts, United Kingdom,HP1 1LF.</p>

<p><b>Note:</b>This Invoice was generated by  Workstation CRM and Invoicing system automatically.</p>
<div class="date">Date: 18/11/2021</div>
<div class="time"> Time: 22:30:05</div>

</body>';


//

$mpdf->WriteHTML($nokhtml . $termsHTML);


//

$mpdf->Output();


?>